### ISSUE TITLE
Cardboard Design Lab

### ISSUE THREAD

**Issue by stuartpb** [omgmog/uxofvr.com#13]
This should probably have an "Apps" section with VR apps that convey VR design principles, like Google's Cardboard Design Lab:

https://play.google.com/store/apps/details?id=com.google.vr.cardboard.apps.designlab

**Comment by omgmog** [comment]
That's a good suggestion, but for it to have its own section would be a bit weird. I think if there are a couple more examples of practical/applied VRUX theory this would be a good idea for a section.

I'm working on tagging the rest of the resources with more meta information, at which point I think having related materials (such as this being related to [Google's VR spec](https://www.google.com/design/spec-vr/designing-for-google-cardboard/a-new-dimension.html)) would be great.

Thanks for your suggestion.
