### ISSUE TITLE
/r/VRUI

### ISSUE THREAD

**Issue by stuartpb** [omgmog/uxofvr.com#14]
There should probably be a "Communities" section with links to forums where people are swapping VR UX links like https://www.reddit.com/r/VRUI/

**Comment by omgmog** [comment]
Some more useful stuff that doesn't necessarily belong on the uxofvr.com list:

- [VR Awesome List](https://github.com/Vytek/VR-Awesome)
- [Organizing the VR Industry 2016 Trello Board](https://github.com/omgmog/uxofvr.com/issues/38)
