### ISSUE TITLE
RSS feed / email newsletter?

### ISSUE THREAD

**Issue by dragGH102** [omgmog/uxofvr.com#17]
I love the concept behind this website. I'd find very cool to be able to receive new articles by email (or via rss).
Is that possible?
I'm also open to use a crawling tool do generate the newsletter (if you know one).

Thanks a lot and keep up the good work!

**Comment by omgmog** [comment]
Right now it's a very simple static site. You could use a service such as [Change Detector](https://www.changedetection.com/) to email you when updates are detected.

As I'm using Git to make changes, starring the repo will ensure that you get notified of each change

Cheers, glad you've enjoyed it!
