### ISSUE TITLE
Suggested resources on hand tracking

### ISSUE THREAD

**Issue by mattnewport** [omgmog/uxofvr.com#21]
[Hand Tracked Controls in VR - The Basics](http://blog.mattnewport.com/hand-tracked-controls-in-vr-the-basics/)
[Hand Tracked Controls in VR - Throwing](http://blog.mattnewport.com/hand-tracked-controls-in-vr-throwing/)

(Disclaimer: I'm the author of these blog posts)

**Comment by omgmog** [comment]
Great stuff. Thanks! 👍
