### ISSUE TITLE
Improv, Not Screenplays: Iterative Holographic Design

### ISSUE THREAD

**Issue by davecurry** [omgmog/uxofvr.com#24]
Slides suggestion!

http://www.slideshare.net/davecurry/improv-not-screenplays-iterative-holographic-design

Designing and developing for HoloLens shatters the existing paradigms that we as designers and developers rely on. As early Microsoft HoloLens partners, Dave Curry and Eric Rak were invited to speak at Build, Microsoft’s annual conference, to provide useful insight for team leaders preparing to begin working with HoloLens.

**Comment by omgmog** [comment]
This looks like a really interesting talk. I don't suppose you've got a recording of it being presented?

**Comment by davecurry** [comment]
Funny story, we presented this talk at CreativeMornings Seattle and it was
recorded, but I found out the video guys lost the HD it was recorded on.
We're going to try and get a recording of it sometime!
