### ISSUE TITLE
intel realsense scene perception

### ISSUE THREAD

**Issue by shacharoz** [omgmog/uxofvr.com#26]
ToyZ 
augmented reality open world game

gameplay: https://www.youtube.com/watch?v=btwU_pT-tao

talk: https://www.youtube.com/watch?v=5TYbx8-ocOI

slides: http://www.slideshare.net/shachar_oz/toys-published

**Comment by omgmog** [comment]
This is really cool and interesting, but not enough about the UX of VR. Thanks for sharing! 👍
