### ISSUE TITLE
Goodbye Metaphors, Hello World - Interface Design in Virtual Reality

### ISSUE THREAD

**Issue by austinmwi** [omgmog/uxofvr.com#28]
Link here:

https://medium.com/yvr/goodbye-metaphors-hello-world-interface-design-in-virtual-reality-d2462e52a029#.w5uk33lht

Hope you like it :D (I wrote it)

**Comment by omgmog** [comment]
Good stuff, I'll get this added soon! 👍

**Comment by austinmwi** [comment]
Righteous, love the list!

**Comment by omgmog** [comment]
Added in 2be36bd3e64d4136ddf4ab21c53c07101ee66253
