### ISSUE TITLE
Gaming sites

### ISSUE THREAD

**Issue by Mroovka** [omgmog/uxofvr.com#30]
Hi Max,
Here are some sites on gaming and accessibility I've collected that you might like to add to your the UX of VR list. Your site is awesome and comprehensive resource, by the way, so some of the links I've bookmarked might already be there.
http://del.icio.us/rmitaccessibility/gaming

cheers
Iza

**Comment by omgmog** [comment]
Thanks for the suggestion, I've had a look through and have added the "Game accessibility guidelines" as this will also apply to VR.

Cheers!
