### ISSUE TITLE
VR UX Book

### ISSUE THREAD

**Issue by cfictum** [omgmog/uxofvr.com#31]
Hey there! the site you put together is awesome. I am leveraging it to improve the content in the book project I've worked on - VR UX.  I was looking all over for a starting point in VR UX and couldn't find anything. So I wrote this book as a starting point by combining all the knowledge I could from VR podcasts, blogs and tutorials.

I usually don't plug my own work - but I think this fits in well with the content offered on your site - I realize that I'm self-published - I'd be willing to send you a free copy if you want to test the waters and make sure it's worth a shout out on VR UX. Just let me know. Thank you and have the best day!

https://www.amazon.com/VR-UX-Learn-Storytelling-Design/dp/1533273022/ref=sr_1_1?ie=UTF8&qid=1470718440&sr=8-1&keywords=vr+ux

**Comment by omgmog** [comment]
Hey Casey, that's really awesome. It's great to see books on the UX of VR coming out.

I've just bought a copy of the Kindle ebook to check out, so I'll get it on the list shortly.

Keep up the good work. Cheers!
