### ISSUE TITLE
"Don't teleport. Fly!"

### ISSUE THREAD

**Issue by andrele** [omgmog/uxofvr.com#32]
Great VR resource! I recently created an ["Iron man" style VR demo](http://hvrga.me) to push the boundaries of VR locomotion and had to deal with several major issues with simulation sickness. The demo ended up being really successful so I wrote about my process on eliminating simulation sickness here:
https://medium.com/yvr/dont-teleport-fly-b175a5c8fd73#.ygw18pn2d

I'd love to be a part of the collection of wonderful articles here!

**Comment by omgmog** [comment]
Nice article, cheers!
