### ISSUE TITLE
Mark Whats been watched

### ISSUE THREAD

**Issue by smassagee** [omgmog/uxofvr.com#33]
It would be nice when we click on a link it will let us know when we watch? I find myself clicking on the same link and then realizing I've watched it. So I've gotta go through everything I watched until I find one I have not. I noticed links that take you to an external website turn black, but if it's a video that will pop up on the website is stays green.

**Comment by omgmog** [comment]
Hi there, this one seemed to have slipped past my attention! I'll see what I can do about this.

**Comment by omgmog** [comment]
Alright this should be addressed in bebfc6044ae1430f41d8bf184652a1de8ffdd5f5

Your resource viewing/reading is now stored locally in your browser (using `localStorage`).
