### ISSUE TITLE
Organizing the VR Industry 2016 Trello Board 

### ISSUE THREAD

**Issue by caitlinmk** [omgmog/uxofvr.com#38]
[This trello board has an extensive list of all the VR things happening in the world right now.  ](https://trello.com/b/srhdQF14/virtual-reality-industry-2016)

You can look at all the supported engines, new input types, headsets, etc.

**Comment by omgmog** [comment]
Hi, this seems like a useful resource, but it's a bit too general to go on the list. Thanks for sharing!

**Comment by erinjerri** [comment]
So we can't include general infograkhucs unless it's UC or design specific in VR?
