### ISSUE TITLE
VR Slides and Speaker Notes

### ISSUE THREAD

**Issue by swapnilborkar** [omgmog/uxofvr.com#42]
Hey there, I thought your list could benefit from a few slides I've made with the help of the Google Cardboard Design Labs app along with speaker notes. This was for a conference and I continue speaking on things happening in VR and UX here and there.

You can have the others access the same through here: https://drive.google.com/drive/folders/0B5HxukasM-KiSjFPaEJELWRxbkU?usp=sharing

I believe this will be very useful for speakers who would want a collaborative resource in a workshop which will contain exercises.

**Comment by omgmog** [comment]
Hey thanks for this, looks like an interesting talk -- will be added in the next update!
