### ISSUE TITLE
Multiplayer approach to collaborative decision-making

### ISSUE THREAD

**Issue by andrele** [omgmog/uxofvr.com#43]
Just wrote a bit about a design concept on how multiplayer VR could be used in a real-world scenario such as AirBnb. Hope you like it!

https://medium.com/yvr/a-multiplayer-approach-to-collaborative-decision-making-9b3e0747112a#.989rm8yhc

**Comment by omgmog** [comment]
Hey that's really interesting. I'll add it in my next update, thanks!
