### ISSUE TITLE
Sustainable Ux in VR

### ISSUE THREAD

**Issue by Martin-Pitt** [omgmog/uxofvr.com#45]
This presentation and the links within lead to more VR UX articles and learnings:

https://docs.google.com/presentation/d/1OTXaz3RuV0HWgM754PRMUC7d2KYVHH974s5hnAt53wk/edit?usp=sharing

**Comment by omgmog** [comment]
Martin thanks for sharing that, they look like great slides. 

I'll add them in the next update. Cheers 👍
