### ISSUE TITLE
Suggestion: Hover UI Kit

### ISSUE THREAD

**Issue by zachkinstner** [omgmog/uxofvr.com#47]
Hi @omgmog, thanks for putting this list together! I'd like to suggest a project of mine:

**Hover UI Kit** (http://HoverVR.com) is a development tool for building VR/AR-friendly user interfaces. It uses a simple "hover" interaction for controlling interface items, and makes heavy use of visual indicators to communicate proximity and selection progress. This kit supports many different 3D input devices, and strives for consistent and reliable interactions (across item types and across different devices). It's open-sourced right here on GitHub :)

![Hovercast animation](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Images/InterfaceModule-Hovercast-LeapMotion.gif)
> _Hovercast is a pre-built "interface module" provided with Hover UI._

Some other content related to Hover UI:
- Guest posts at the Leap Motion blog, covering the UI/UX thinking behind Hover UI: ["Behind the Design"](http://blog.leapmotion.com/hovercast-vr-menu-behind-design) and ["Power At Your Fingertips"](http://blog.leapmotion.com/hovercast-vr-menu-power-fingertips).
- An early "Hovercast" (hand-based menu interface) [video](https://www.youtube.com/watch?v=Phn3Ix-YxPA&list=PLmUZ4l5SqKXwEOPROtTJJBFURhIHkWDos&t=5s&index=1).
- "VR Guitar" [video series](https://www.youtube.com/playlist?list=PLmUZ4l5SqKXxVdI8GNld1-YZRClvu-ljw) and "Force-Directed Graph" [video series](https://www.youtube.com/playlist?list=PLmUZ4l5SqKXwWiIscqatn0cMyGX3llZZP) show uses of Hover UI. These discuss UI/UX thinking, decisions, and technical challenges faced along the way.

**Comment by omgmog** [comment]
Good stuff! Added in 8a0b935d85a059db6263fcdbd0adddb8899847ae
