### ISSUE TITLE
2 new articles

### ISSUE THREAD

**Issue by TagoWill** [omgmog/uxofvr.com#54]
Simple tutorial on [Creating a basic VR demo using Unreal](https://virtualrealitypop.com/start-a-vr-demo-using-the-unreal-engine-63d31eeaf784)
and  [VR games & apps — Where to sell?](https://virtualrealitypop.com/vr-games-apps-where-to-sell-2127697bb70c)
Written by me.

**Comment by omgmog** [comment]
Hi Tiago

These are good articles, but they're not about the UX of VR so I can't add them to the list.

Thanks for sharing though, and thanks for writing them!

Cheers
