### ISSUE TITLE
I get lost with the video list.

### ISSUE THREAD

**Issue by patribezek** [omgmog/uxofvr.com#55]
Hello Max!

I'm watching the videos in your webpage http://www.uxofvr.com/#video, but when i get to sleep, or go for a cup of tea, i get lost. Can you please enumerate them or i don't know, maybe generate a gradient with colours, or set a cookie for a week with checkboxes or something like that? I appreciate a lot your work and i wouldn't miss something!
Tanks in advance, kind regards, 
Patricia.

**Comment by omgmog** [comment]
Hi Patricia

I'm currently working on a nice way to improve the UX of the site to help with this.

I'll continue the discussion in issue #33 and close this one for now.

Thanks for taking the time to suggest this improvement!

Cheers,
Max
