### ISSUE TITLE
I would love to know who is working on an AR prototype tool...

### ISSUE THREAD

**Issue by siilka** [omgmog/uxofvr.com#59]
....that is super quick and collaborative? IE. Not Unity or Unreal. Thanks, Silka

**Comment by omgmog** [comment]
Hi Silka,

You might find that [A-Frame](https://aframe.io/) is what you're looking for. With this you can use a pseudo-HTML and JavaScript to create 3D scenes quickly and relatively easily: https://aframe.io/

An alternative (though targeted at VR) is [Co-spaces](https://cospaces.io/) -- this allows you to create 3D scenes with a drag and drop interface: https://cospaces.io/

Here are some resources for approaches to AR prototyping:
- http://www.slideshare.net/marknb00/rapid-prototyping-for-augmented-reality
- https://medium.com/momentary-exploration/prototyping-for-augmented-reality-ffc724a679b2#.qklzxwhtv
- http://eu.wiley.com/WileyCDA/WileyTitle/productCd-1118036638.html
- https://blog.prototypr.io/tagged/augmented-reality


Cheers
Max

**Comment by siilka** [comment]
Thanks so much Max. So helpful!

---
*Silka Miesnieks | +1 415 819 7292 | @silkamiesnieks*

**Comment by lebek** [comment]
Hi Siilka - I built Sketchbox (http://sketchboxvr.com/) which might solve your problem assuming you have access to Vive or Rift+Touch.

@omgmog is there space for a "tools" section?
