### ISSUE TITLE
Augmented Reality: A class of displays on the reality-virtuality continuum

### ISSUE THREAD

**Issue by sawthinkar** [omgmog/uxofvr.com#61]
Category: Article
[Augmented Reality: A class of displays on the reality-virtuality continuum](http://web.cs.wpi.edu/~gogo/hive/papers/Milgram_Takemura_SPIE_1994.pdf)
http://web.cs.wpi.edu/~gogo/hive/papers/Milgram_Takemura_SPIE_1994.pdf
Paul Milgram, Haruo Takemura, Akira Utsumi and Fumio Kishino

**Comment by omgmog** [comment]
Hey Saw! Thanks for sharing this. 

I'll add this in the next update. Cheers!
