### ISSUE TITLE
Frontiers of Virtual Reality User Experience

### ISSUE THREAD

**Issue by moasama6** [omgmog/uxofvr.com#62]
Hi Max, I'm the founder of Amped-UX, a design consultancy in Southern California / LA specializing in VR UX Design.  Love your site and your list.  I've given some talks on VR UX Design so I wanted to share the video and the slides.  Here you go!

[Socal UX Camp Youtube Playlist Link]
(https://www.youtube.com/watch?v=-f2OgAyjDVU&list=PLA27jL5mOsuXdOup1ejEJ3h1L1cWTgGJr)

[Google Slides Link - Work in progress - lots of fast-moving developments in VR as you know!]
(https://docs.google.com/presentation/d/1TMbvwudDoWX-uy951HppecInbbyJwzAIGMu5w_l4Fj4/edit?usp=sharing)

Feel free to connect with my on [LinkedIn](http://linkedin.com/in/ejm3d) or drop me a note at ed.moore@amped-ux.com - please let me know if you find the content interesting and decide to list it.  I'd be happy to set-up a social media blast to promote your site.  Thank you again!

Best,

-Ed Moore

**Comment by omgmog** [comment]
Hey Ed -- this is really great, thanks! I'll add them in the next update. Cheers!
