### ISSUE TITLE
Methods of Analyzing Your VR Experience

### ISSUE THREAD

**Issue by alllesss** [omgmog/uxofvr.com#63]
I wrote an article about Analyzing a VR Experience and thought it's relevant to uxofvr..

https://medium.com/@alless91/methods-of-analyzing-your-vr-experience-dbdfe0ea2edd#.3xspdvz5k

**Comment by omgmog** [comment]
Hi Ali
That looks great. I'll give it a read and add it to the list in the next update.

Cheers!
