### ISSUE TITLE
Simulated Reality

### ISSUE THREAD

**Issue by sawthinkar** [omgmog/uxofvr.com#64]
Category: Videos
[Simulated Reality](https://www.youtube.com/watch?v=K4rCzA8fS84)
https://www.youtube.com/watch?v=K4rCzA8fS84
LEMMiNO

Quite interesting explanation on the philosophy of VR

**Comment by omgmog** [comment]
Thanks for sharing the video -- though it's great, it's a bit too general to go on the UX of VR list.
