### ISSUE TITLE
What are Virtual and Augmented Realities?

### ISSUE THREAD

**Issue by sawthinkar** [omgmog/uxofvr.com#65]
Category: Videos
[What are Virtual and Augmented Realities?](https://www.youtube.com/watch?v=f9MwaH6oGEY)
https://www.youtube.com/watch?v=f9MwaH6oGEY

ColdFusion YouTube video in collaboration with UploadVR

**Comment by omgmog** [comment]
Thanks for sharing this, I think it's a bit too general/broad for the list as it doesn't really talk about creating good UX in VR. 

Thanks again
