### ISSUE TITLE
Typos and inconsistent style

### ISSUE THREAD

**Issue by 12people** [omgmog/uxofvr.com#81]
Please correct these typos:
- Principals -> principles
- Intuitative -> intuitive
- RealityDesign -> Reality: Design

Also, it'd be nice if capitalization was consistent throughout the page. Right now, there's not only inconsistency between headings, but also within individual headings.
For example:
- "Motion, focus, control… Exploring the UX of Virtual Reality"—the heading starts with sentence case, then jumps into title case
- "4 Things I learned Designing User Interfaces for VR at Disney."—I'm guessing title case was the intention
- "Augmented Reality: A class of displays on the reality-virtuality continuum"—augmented reality isn't a proper noun, capitalization after a colon for phrases is recommended against

**Comment by omgmog** [comment]
Hi Mirek

Apologies for the delay in picking this issue up... That's a good eye for detail!

The typos should now be fixed on the site. As for capitalization in resource titles, I've not really got a style guide set out for this -- the resource titles are usually just taken directly from the resource.

I've got a bunch of resources to add, so I might have a think about that going forward.

Thanks for taking the time!

Cheers
Max
