### ISSUE TITLE
New suggestion - Mobile VR IxD

### ISSUE THREAD

**Issue by m-uhr** [omgmog/uxofvr.com#83]
Hey guys!

I wrote my Master Thesis about User Experience and Interaction Design for Mobile VR. The patterns I found might be interesting for you, I studied lots and lots of Mobile VR Apps and described how I designed my own. Unfortunately it's written in German, but for some of you it might be helpful though. :-)

The source: http://edoc.sub.uni-hamburg.de/haw/volltexte/2017/3907/
The pdf: http://edoc.sub.uni-hamburg.de/haw/volltexte/2017/3907/pdf/MasterThesis_MUhr_2153565.pdf

I might also upload it on my personal site soon.
Have fun!

**Comment by omgmog** [comment]
Hi Uhr!

That's great, and such an interesting topic for your Master Thesis - I'm thinking about adding a non-English section to the site, so will definitely consider this then!

Thanks for taking the time to share

Cheers
Max
